Better map for signals
hyperspy/hyperspy pull request #1295
Opened 2016-09-16 10:55 UTC by to266

- Separates `map` into two functions that can later be replaced for lazy signals
 - As a bonus, running the `map` in parallel (threaded, not multi-process manner) was trivial to add.

## TODO:
 - [ ] threaded tests to ensure identical behaviour

2016-11-22 15:51 UTC, to266 commented
Ready for review

2016-11-24 18:32 UTC, francisco-dlp requested changes
Apart from the minor component this looks very good to me, except that

* [ ] The new feature needs to be documented in the User Guide
* [ ] All calls to `map` in the rest of the code should have the extra `threaded` keyword.

By the way, would it make sense to add `threaded` to `preferences.General`?

2016-11-24 18:32 UTC, francisco-dlp commented on hyperspy/model.py
> +        threaded : bool, int
Why not `parallel` or something of this sort that will be more telling to non-programmers?

2016-11-24 18:32 UTC, francisco-dlp commented on hyperspy/signal.py
> +        threaded : bool
As above

2016-11-26 00:27 UTC, to266 commented
Added as requested

2016-11-28 09:52 UTC, francisco-dlp commented
All looks good to me. Could you update your branch with RELEASE_next_patch to see if Appveyor and travis are happy too?

2016-11-28 10:31 UTC, to266 commented
I just did!

2016-11-28 11:03 UTC, francisco-dlp commented
Tests are failing...

2016-11-28 13:53 UTC, to266 commented
Yep, though I can't reproduce this locally. I'll hopefully figure it out on the next "break"

2016-11-28 14:34 UTC, francisco-dlp commented
After upgrading anaconda (`conda update anaconda`) I am able to reproduce the issue locally.

2016-11-28 16:51 UTC, to266 commented
Seems to have worked. At the same time added notebook progressbar to be used if possible (have been using this for a long time, just never PRed..)

2016-11-28 17:13 UTC, francisco-dlp approved these changes

2016-11-28 17:13 UTC, merged