Fix #1318: bug saving eels without metadata in rpl files
hyperspy/hyperspy pull request #1324
Opened 2016-11-08 23:03 UTC by ericpre

- Fix #1318 
- Add tests reproducing the bug.

Saving EELS signal without the `Acquisition_instrument` metadata was not working as explained in #1318. It should be possible to save EELS signal without to have to set the `Acquisition_instrument` metadata. EDS signal was saving fine.

2016-11-14 14:07 UTC, mwalls commented
Thanks Eric

2016-11-18 09:59 UTC, francisco-dlp commented
Thanks for the fix. Other than the comment above, this is ready to merge.

2016-11-18 15:18 UTC, ericpre commented
Hi Francisco, sorry I don't see the comment you are mentioning!

2016-11-18 15:23 UTC, francisco-dlp requested changes

2016-11-18 15:23 UTC, francisco-dlp commented on hyperspy/tests/io/test_ripple.py
> +def test_save_ripple_EELS_signal_no_metadata():
Why not modifying the existing functions in order to test saving without metadata instead of writing new ones. For example,  you could add a boolean `metadata` argument to `_create_signal` and `_run_test` and an extra line to `test_ripple` e.g. `for metadata in (True, False)`. This is just a matter of style to make the code more compact and easier to read.

2016-11-18 15:24 UTC, francisco-dlp commented
Sorry, I've forgotten to submit the review.

2016-12-21 20:25 UTC, ericpre commented on hyperspy/tests/io/test_ripple.py
> +def test_save_ripple_EELS_signal_no_metadata():
done!

2016-12-22 09:36 UTC, merged