Linearity attribute to parameters
hyperspy/hyperspy pull request #1453
Opened 2017-02-15 13:24 UTC by thomasaarholt

This is a stepping stone towards a smarter fitting method, where the fitter can recognise whether or not all parameters are linear and so use linear fitting (much much faster). Now all parameters have a `is_linear` boolean attribute.

I am uncertain about the correct approach to the expression component
(currently set any parameter’s is_linear to False).

I am also unsure about which parameters are linear for the heaviside,
voigt, RC, PESCORELineShape (with shirley) and EELS_vignetting, though I've given it my best guess.

2017-02-15 14:22 UTC, tjof2 commented
I think you're right with the `voight` model - it's based on a convolution isn't it?

2017-02-23 11:39 UTC, thomasaarholt commented
It would be great if someone could take a look at the components mentioned above - I am rather unfamiliar with them.

2017-04-09 16:37 UTC, thomasaarholt commented
Right, I've had a play with the components, and as far as I can tell, the linearity attributes are set correctly. The components reported in #1583 don't work at all, so I'm less concerned about them anyway.

In any case, where I have been uncertain I have set the parameter not free, so that a nonlinear fitter will be defaulted.

I think this is ready to merge.

2017-04-09 18:13 UTC, ericpre commented
It breaks a couple of tests. What's the reason?

2017-04-09 18:40 UTC, thomasaarholt commented
You're right. I hadn't been paying attention to it because something else had been failing PR tests previously.

2017-04-09 19:32 UTC, thomasaarholt commented
Not sure why this commit created a conflicting file. Resolving it now.

2017-04-09 19:38 UTC, thomasaarholt commented
In the future, fitting tools should assume the fitting is not linear if the `is_linear` attribute is not present, as it could be on a manually created component.

2017-04-09 21:41 UTC, to266 commented on hyperspy/_components/expression.py
> +        for parameter in self._parameter_strings:
why such a convoluted way? why not just
```python
for par in self.parameters:
    par.is_linear = False
```
at this point the component is close to just normal ones and populated.

2017-04-09 21:43 UTC, to266 commented
Generally I would add default for every new parameter that it is not linear, and then remove all unnecessary explicit `is_linear=False`.

2017-04-09 21:44 UTC, thomasaarholt commented on hyperspy/_components/expression.py
> +        for parameter in self._parameter_strings:
Thanks... I thought I had tried that initially and it didn't work. I must have confused myself somehow. Will fix tomorrow.

2017-04-09 21:46 UTC, thomasaarholt commented on hyperspy/_components/expression.py
> +        for parameter in self._parameter_strings:
I had it that way initially, but had the code under the wrong method.

2017-04-09 21:46 UTC, thomasaarholt commented
Good point @to266. Won't need the expression is_linear at all then.

2017-04-11 17:31 UTC, francisco-dlp commented
It should be possible to determine automatically if a parameter is linear using sympy.

2017-04-12 17:18 UTC, thomasaarholt commented
Just leaving this here for later as I am on the move:
http://stackoverflow.com/questions/36283548/check-if-an-equation-is-linear-for-a-specific-set-of-variables/36290758


On Tue, 11 Apr 2017 at 19:31, Francisco de la Peña <notifications@github.com>
wrote:

> It should be possible to determine automatically if a parameter is linear
> using sympy.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hyperspy/hyperspy/pull/1453#issuecomment-293338091>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACmGj3fBM-6Cez-JVrPewowxSeg-S-gsks5ru7jxgaJpZM4MBtcg>
> .
>

2017-04-13 11:14 UTC, thomasaarholt commented
There we go! Sympy support for checking expression linearity. Added tests.

Ready for review.

2017-04-13 11:46 UTC, to266 commented on hyperspy/_components/expression.py
> +    def is_linear(self, expr, vars):
I would move this function out of the class.

Also I don't think it needs to be as general as it is in the stackexchange example:
```python
def is_linear(expression, name):
    try:
        return sympy.Eq(sympy.diff(expression, name, 2), 0)
    except TypeError:
        return False

2017-04-13 13:46 UTC, thomasaarholt commented
Agreed on both accounts. Your code suggestion needed a modification to work properly.

2017-04-13 15:35 UTC, to266 commented on hyperspy/_components/expression.py
> +    return True
I still think this needs a rewrite in the form I suggested previously (while obviously keeping the first check that the parameter is indeed in the expression).

Currently this reads:
```python
try:
    if not True:
        return False
    else:
        return True
except:
    return False
```

Which is clearly simpler this way:
```python
try:
    return [True/False] # the actual bool statement here. Add "not" if needed, which I don't think you do
except:
    return False
```

2017-04-13 22:29 UTC, thomasaarholt commented
I've realised the code I was using for checking linearity was checking the wrong thing. I've updated the tests.

@to266, since the "check" code is now entirely different, would you mind looking over it again?

2017-04-14 08:09 UTC, francisco-dlp commented
The current implementation of ``Expression.is_linear`` may still not be what we need. I'll show it with two examples:

```python

>>> e = hs.model.components1D.Expression("a * b * x", name="linear")
>>> e.a.is_linear
True
>>> e.b.is_linear
True

```

However lls can only solve a model with this component if ``a`` or ``b`` is constant (i.e. ``free is False``).

```python

>>> e = hs.model.components1D.Expression("a  * x + b", name="linear")
>>> e.a.is_linear
False

```
Here the component is a linear equation of the sort that lls can solve, but ``is_linear`` returns ``False``. This is correct, ``a`` is indeed not linear in this sense, but this is not the sort of linearity that matters in our case.

Let's forget about linearity for a moment and let's see what we need to know for running lls or not. As lls solves systems of linear equations of the form ``k1 * x1 + k2 * x2 + ... kn * xn = b1``, when dealing with an individual component we must check:

1. Is the component (not the parameters) linear i.e. are the **free** parameters jointly linear? In  general, the answer to this question would depend on which parameters are free at the time of fitting. I think that the stack overflow code of the original implementation of ``Expression.is_linear`` is a good way to check for this, where the ``vars`` are the free parameters.
2. Does the component contains a constant? If yes, it should be added to the constant of the lls model (``b1`` above). For example, in ``a * x +b ``, if ``b`` is not free, then the component has a constant term. As we are solving ``Y = A X + B`` where ``Y`` is the data, the fitting routine should extract the constants of all components, sum them and subtract them from ``Y``. So, probably it'll be good to add a ``constant_term`` property to the component.

Regarding all the other components, I would make the ``Parameter._is_linear`` attribute private and add a ``Component.is_linear`` property that checks if all free components have ``_is_linear == True``, which should be correct for most components. Also add a ``constant_term`` property that simply returns 0 and doesn't allow setting the value. However, if any component linearity is  "non-trivial", the component should redefine the ``is_linear`` property in order to take into account "non-joint-linearities" and the ``constant_term`` property.

Does it make sense?

2017-04-14 13:22 UTC, thomasaarholt commented
Absolutely. Thanks for such a comprehensive post. This is definitely turning into a bigger PR than I anticipated and I'm very glad to have people checking in on me!
Having a go at this this weekend.

2017-04-17 10:12 UTC, thomasaarholt commented
I've got a draft for the new approach. I think I've finished the expression component. Could someone please look through the code for it? It seems to work fine, but this is my first time working with `@property`, so I'd appreciate it if someone could give me some feedback.

For the remaining components I still need to check the `constant_term`, which for now is 0 for any new component.

2017-04-18 16:20 UTC, francisco-dlp commented
I just made a small test:


```python

>>> import hyperspy.api as hs
>>> e = hs.model.components1D.Expression("a * b * x + c", "test")
>>> e.is_linear
True
```

Shouldn't it return ``False`` when all parameters are free (default)?

2017-05-12 09:35 UTC, thomasaarholt commented
Right. One major change now is the introduction of the term "independent", to refer to parameters that are independent of the signal axes (that is, `x` in expressions, the energy axis in EDS/EELS, etc).

**`component.independent_parameters`** lists these parameters in a similar fashion to `component.parameters` and `component.free_parameters`:

```python
>>> comp = Expression("a * b * x + c*d", "test")
>>> comp.independent_parameters
[<Parameter c of test component>, <Parameter d of test component>]
```

**`component.independent_term`** returns the calculated value of the independent term in the component, substituing the independent part of the expression for the `parameter.value`s. For the expression `x + b`, it would return b.value. 

```python 
>>> comp.c.value = 20
>>> comp.d.value = 2
>>> comp.independent_term
40.00
```

It returns 0 for most components (as they do not have an independent term). In the linear_fitting PR, I am intending to include some form of `model.independent_term` to sum the value of the independent_term for all components in the given navigation indices.

2017-05-12 09:35 UTC, thomasaarholt commented
@francisco-dlp The cases you suggested are covered by tests - but do feel free to suggest more or poke other holes in the code!!!

2017-05-24 17:27 UTC, francisco-dlp requested changes
Except for the small comments, it LGTM

2017-05-24 17:27 UTC, francisco-dlp commented on hyperspy/_components/pes_core_line_shape.py
> +        self.A._is_linear = False # This is probably linear, but unsure
Yes, I think that this one is linear

2017-05-24 17:27 UTC, francisco-dlp commented on hyperspy/component.py
> +        if len(self.free_parameters) > 1:
This method can be simplified:

```python
if len(self.free_parameters) == 1:
    return self.free_parameters[0]._is_linear
else:
    return False
```

2017-05-24 17:27 UTC, francisco-dlp commented on hyperspy/component.py
> +    def _check_only_one_linear_parameter(self):
Isn't this function unnecessary? The component can't be linear if the number of free parameters is > 1.

2017-05-24 17:27 UTC, francisco-dlp commented on hyperspy/tests/component/test_independent.py
> +def test_independent_after_fit():
What's the point of this test?

2017-05-25 10:45 UTC, thomasaarholt commented on hyperspy/component.py
> +        if len(self.free_parameters) > 1:
This one was nice. Thanks!

2017-05-25 10:47 UTC, thomasaarholt commented on hyperspy/tests/component/test_independent.py
> +def test_independent_after_fit():
You're right, and I actually wasn't using it anyway.

2017-05-25 10:49 UTC, thomasaarholt commented
Corrected your comments. Thanks @francisco-dlp .

2017-05-25 10:49 UTC, thomasaarholt commented on hyperspy/component.py
> +    def _check_only_one_linear_parameter(self):
You're right, and I actually wasn't using it anyway.

2017-05-25 10:50 UTC, thomasaarholt commented
Oops, accidentally deleted your test comment.  Hang on.

2017-05-25 10:56 UTC, thomasaarholt commented
Checking my email to see what you wrote about it:
> In hyperspy/tests/component/test_independent.py:
> 
> > +        sigma = 1.0)
> +    assert g.independent_term == 0
> +
> +def test_independent_from_expression3():
> +    expression = "a * b * x + 10**(c/d) + e"
> +    g = Expression(
> +        expression, 
> +        name="test_constant",
> +        a = 20.0,
> +        b = 4.0,
> +        c = 10.0,
> +        d = 2.0,
> +        e = 20.0)
> +    assert g.independent_term == 10**5 + 20
> +
> +def test_independent_after_fit():
> What's the point of this test?
> 
Which test were you referring to?

test_independent_from_expression2 checks that the independent term indeed is zero for an expression where it should be zero. test_independent_from_expression3 ensures that one with multiple variables not depending on x are added correctly.

Right, looking at the last one, "test_independent_after_fit", I think I see what you mean. It's already handled by the previous test. Deleting, then we're good.

2017-05-25 13:57 UTC, francisco-dlp commented
As there is no time to get #1321 in for v1.3, I suggest to leave this one for v1.4 too as its raison d'être is  #1321

2017-05-25 17:14 UTC, thomasaarholt commented
Fully agreed.

2018-01-24 19:26 UTC, thomasaarholt commented
Closing this as it is merged into #1462.

2018-01-24 19:26 UTC, closed without merging