Fix post checkout githook
hyperspy/hyperspy pull request #1566
Opened 2017-04-04 12:05 UTC by vidartf

Fix the post checkout git hook, such that all paths for `rm` gets quoted. Without this, something could go wrong if e.g. the repository is in the path `C:\windows development files\hyperspy` (will try to delete `C:\windows`, `development` and `hyperspy/hyperspy/io_plugins/unbcf_fast.c`).

Note: That command should not actually do anything since `rm` should not delete folders, but you get my drift.

An alternative is of course to remove the post-checkout code from the setup.py code, and make it an opt-in feature instead. I would argue that installing hooks automatically is a little confusing (and possibly rude).

Someone will have to confirm if this quoting (double quotes) will work safely on other OSes than Windows.

2017-04-05 00:53 UTC, erh3cq commented
Still having the issue
"""
~\Documents\GitHub\hyperspy [Mule ≡]> git checkout RELEASE_next_minor
Your branch is up-to-date with 'origin/RELEASE_next_minor'.
Switched to branch 'RELEASE_next_minor'
rm: cannot remove 'C:/Users/Eric Hoglund/Documents/GitHub/hyperspy/hyperspy/io_plugins/unbcf_fast.c*': No such file or directory
rm: cannot remove 'C:/Users/Eric Hoglund/Documents/GitHub/hyperspy/hyperspy/io_plugins/unbcf_fast.cpython-*.pyd': No such file or directory
.git/hooks/post-checkout: line 4: C:/Program: No such file or directory
"""

2017-04-05 08:13 UTC, vidartf commented
Well, those are OK if the files actually do not exist.

2017-04-05 08:14 UTC, vidartf commented
I.e. if they were not previously built.

2017-04-05 13:38 UTC, erh3cq commented
the files are named uncb_fast.c and uncb_fast.pyx
So the first remove should work?
The second should be pyx not .pyd?
The last remove seems to be attempting to remove the file from C:/Program not .git/hooks

2017-04-05 13:57 UTC, vidartf commented
The last line is actually not a removal command, but I guess that should get quotes as well.

2017-04-05 15:06 UTC, sem-geologist commented
@vidartf  I agree that all this githook is terrible mess, I were thinking to remove it completely, but still not thought up the replacement... Maybe `.hook_ignore` file should be created by default in the source tree, then by default that post checkout hook would not work.
It should go away from setup.py, it does complicate it too much.

2017-04-05 15:11 UTC, erh3cq requested changes
Can we make 185&186 have quotes? On windows it is searching for C:\Program Files, but that contains spaces.
227 needs quotes?

I am wondering, would it be better to use .replace(' ','%20') rather than quotes on all of these?
-setup_path.replace(' ','%20') near line 47
-git_dir.replace(' ','%20')

2017-04-05 18:52 UTC, erh3cq commented
I have edited the setup file, and it is working.  How do I upload it to here?

2017-04-06 08:10 UTC, vidartf commented
The best solution is to make a PR to my branch ([vidartf:fix-githook](https://github.com/vidartf/hyperspy/tree/fix-githook)).

2017-04-06 14:38 UTC, vidartf commented
Whoops, some commits from minor got included, I'll rebase the branch to sort it out.

2017-04-06 14:39 UTC, francisco-dlp commented
Don't worry about it, the next release will be a minor.

2017-04-06 14:42 UTC, vidartf commented
There might still be some issues left, but this PR should at least be a strict improvement.

2017-04-07 16:31 UTC, merged