Update tools.rst
hyperspy/hyperspy pull request #1591
Opened 2017-04-11 10:06 UTC by mwalls

Trying to fix more links. Hope the ones I've done are ok. But there are some broken ones here I don't know how to fix. (data, original metadata, angle and others).
I'll try and find out unless someone else can see immediately...

2017-04-11 17:11 UTC, francisco-dlp requested changes
Thanks! Just a minor issue to fix.

2017-04-11 17:11 UTC, francisco-dlp commented on doc/user_guide/tools.rst
> +:py:class:`~.axes.:py:class:`~.axes.AxesManager`` attribute.
``py:class:`~.axes.AxesManager``  instead?

2017-04-11 17:11 UTC, francisco-dlp commented on doc/user_guide/tools.rst
> +Many of the values in the :py:class:`~.axes.:py:class:`~.axes.AxesManager`` can be
As above

2017-04-12 07:28 UTC, mwalls commented on doc/user_guide/tools.rst
> +Many of the values in the :py:class:`~.axes.:py:class:`~.axes.AxesManager`` can be
Actally, maybe I somehow changed that last line myself? It seems I did. I'll do it again Sorry.

2017-04-12 15:12 UTC, francisco-dlp commented
Thanks!

2017-04-12 15:12 UTC, merged