Fix spines not showing in mpl backends that support blit
hyperspy/hyperspy pull request #1904
Opened 2018-04-10 15:14 UTC by francisco-dlp

### Description of the change

Some animated artists where not drawn when using the blit drawing method. This fixes it by using ``ax.get_children()`` to generate the previously hard-wired list of artists. Thanks @tacaswell for suggesting this fix in #1890.

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [x] ready for review.

2018-04-10 16:09 UTC, ericpre requested changes

2018-04-10 16:09 UTC, ericpre commented on hyperspy/drawing/figure.py
> +                if hasattr(artist, "animated") and artist.animated:
It looks to me that `get_children()` is making a list with a specific order and the image is drawn on on the widgets, I would suggest:
```python
# Create a list of animated artitst and draw them.
artists = ax.get_children()
# need to put the images at the beginning of the list
if len(ax.images) > 0:
    for image in ax.images:
        artists.remove(image)
        artists.insert(0, image)
for artist in artists:
    if artist.get_animated():
        ax.draw_artist(artist)
```

2018-04-10 20:07 UTC, tacaswell commented on hyperspy/drawing/figure.py
> +                if hasattr(artist, "animated") and artist.animated:
You probably should sort by z-order `artists = sorted(artists, key=attrgetter('zorder'))` rather than hard-coding images at the front.

2018-04-11 07:31 UTC, francisco-dlp commented
@ericpre, you're totally right. I have now fixed the code, but it still doesn't work. For example, when plotting a spectrum image the rectangle pointer is missing, even though the ``get_children()`` returns the patch and ``get_animated()`` is ``True``, hence ``draw_artist`` is executed. I thought that it could be a ``zorder`` issue, but setting the rectangle patch's zorder to 10 didn't help. Maybe the order of execution of ``draw_artist`` for each individual artist matters?

2018-04-11 08:22 UTC, francisco-dlp commented
Plotting as follows:

```python
%matplotlib qt
import hyperspy.api as hs
import numpy as np

s = hs.signals.Signal1D(np.zeros((10, 10, 100)))
s.plot()
```

This is the execution order of the animated artists with this code:

```
Line2D(_line0)
Text(1,8.9,'$2\\,$<undefined>')
Rectangle(xy=(-0.5, -0.5), width=1, height=1, angle=0)
AxesImage(34.5556,59.359;465.278x465.278)
YAxis(528.913194,23.466953)
Line2D(_line0)
Text(-0.1,1.05,'(0, 0)')
XAxis(66.972222,58.277778)
YAxis(66.972222,58.277778)
```

And this is the execution order with the hard-wired list:

```
AxesImage(34.5556,59.359;465.278x465.278)
Line2D(_line0)
Text(1,8.9,'$2\\,$<undefined>')
Rectangle(xy=(-0.5, -0.5), width=1, height=1, angle=0)
YAxis(528.913194,23.466953)
Line2D(_line0)
Text(-0.1,1.05,'(0, 0)')
YAxis(66.972222,58.277778)
XAxis(66.972222,58.277778)
```

The ``zorder`` of the image is 0 and that of the rectangle 1, so the latter should be painted above the image.

2018-04-11 08:57 UTC, ericpre commented
The current version of this branch doesn't set properly the zorder as suggested by @tacaswell, have you forgot to push some commits? I would expect to read something along the line of:
```python
for ax in self.figure.axes:
    # Create a list of animated artitst and draw them.
    for artist in sorted(ax.get_children(), key=attrgetter('zorder')):
        if artist.get_animated():
            ax.draw_artist(artist)
```

2018-04-11 09:10 UTC, francisco-dlp commented
No, I just failed to notice @tacaswell comment this morning when I set to implement the changes that you've suggested yesterday. It should be fixed now.

2018-04-11 09:26 UTC, francisco-dlp commented
I've edited the title and description and removed the bug label as this is finally not fixing any plotting issue.

2018-04-11 11:39 UTC, ericpre approved these changes

2018-04-11 11:41 UTC, ericpre commented
This looks good to me.

2018-04-11 14:05 UTC, francisco-dlp commented
merge it then?

2018-04-11 14:15 UTC, merged