Fix quant scaling error
hyperspy/hyperspy pull request #2090
Opened 2018-11-15 14:41 UTC by k8macarthur

### Description of the change
The dose calculation function used for cross section quantification previously assumed that the units of the navigation axis are in 'nm'. Therefore I've added a check to the function and convert_to_units for when the units are not 'nm'.  

Test to check whether or not different units produces the same quantification results was also added. 

As this is a bug fix no update to the user guide is needed.

2018-11-15 14:44 UTC, k8macarthur commented
This change will not change the units in the original spectrum image, just locally within the function for the correct electron dose to be calculated.

2018-12-01 16:42 UTC, ericpre commented
@k8macarthur I have rebased your branch on Rnp to fix some left over of a merge conflict and the merge commits. You will need to checkout this branch.

2018-12-01 17:26 UTC, ericpre requested changes
Two things need to be fixed:
- not to change the units in place,
- currently `get_dose("cross section")` works only for spectrum image.

See more detailed comments below.

2018-12-01 17:26 UTC, ericpre commented on hyperspy/_signals/eds_tem.py
> +                        self.axes_manager[1].convert_to_units('nm')
This is changing the units in place. The following should work:
```python
pixel_size = []
# in case there are more than 2 navigation axes.
for axis in self.axes_manager.navigation_axes[:2]:                    
    pixel_size.append(axis.convert_to_units('nm', inplace=False)[0])
```
In particularly, for a dataset with navigation dimension > 2, how do we know if we pick the correct navigation axes? Here, I assume that the first two items of the `axes_manager.navigation_axes` are the "x" and "y" spatial dimension but it could something else!
Depending on how this is implemented, this should be documented.

2018-12-01 17:26 UTC, ericpre commented on hyperspy/_signals/eds_tem.py
>                      pixel2 = self.axes_manager[1].scale
By the method to get the dose will be wrong for linescan: `self.axes_manager[1].scale` could be a signal axis..

2018-12-01 17:26 UTC, ericpre commented on hyperspy/tests/signal/test_eds_tem.py
> +        assert s.axes_manager[0].units == 'µm'
This is this assertion which need to be true. At the moment, the units are changed inplace.

2019-05-17 11:56 UTC, ericpre approved these changes

2019-05-17 11:57 UTC, ericpre commented
I have fixed the comments of my review.

2019-05-17 15:20 UTC, francisco-dlp commented
LGTM

2019-05-17 15:20 UTC, merged