Fix issue when loading decomposition results
hyperspy/hyperspy pull request #2094
Opened 2018-11-16 16:02 UTC by dmlundeby

Fix bug causing attributes to be saved as 0D numpy arrays.

Fix by converting the attributes to their original Python datatype.

### Progress of the PR
- [x] Change implemented
- [ ] Add tests
- [x] Ready for review

### Minimal example of the bug fix or the new feature
```python
>>> import hyperspy.api as hs
>>> s = hs.load(multidimensional_eds_signal)
>>> s.change_dtype('float64')
>>> s.decomposition()
>>> s.learning_results.save('results.npz')
>>> s.learning_results.load('results.npz')
>>> s.save('out.hspy')
```

This does no longer cause an error.

2018-12-02 12:20 UTC, ericpre requested changes
See one comment above and a test needs to be added, since this is not tested at all (https://coveralls.io/builds/20147432/source?filename=hyperspy%2Flearn%2Fmva.py#L1258). Your example is good enough, it only needs small adjustments to add it the test suite. For example, to generate a dummy signal, simply use `s = hs.signals.Signal1D(np.random.random((5, 10))) ` and to check if the file save correctly, you can use:

```python
import tempfile
with tempfile.TemporaryDirectory() as tmpdir:
    fname2 = os.path.join(tmpdir, "test_save_load_cycle_learning_results.hspy")
```

2018-12-02 12:20 UTC, ericpre commented on hyperspy/learn/mva.py
> +            if isinstance(value, np.ndarray) and value.shape == ():
Add a comment to explain why we need to do this here.
Also, I would suggest to use `value.size == 1` instead of `value.shape == ()`

2018-12-02 12:23 UTC, ericpre commented
Also since this is a bug fix, it should go to the `RELEASE_next_patch` branch instead of the `RELEASE_next_minor`. You may need to rebase and possibly force push your commits to this branch.

2018-12-02 12:40 UTC, ericpre commented
Fix #2093.

2018-12-05 13:03 UTC, dmlundeby commented
Thank you for feedback! I'll do the fixes after end of semester. 
I did start a test case, but didn't know how to save and load test files properly. I'll add the test using `tempfile`.

2019-01-06 23:08 UTC, dmlundeby commented on hyperspy/learn/mva.py
> +            if isinstance(value, np.ndarray) and value.shape == ():
I think it is best to retain `value.shape == ()` because the issue is only 0D numpy arrays and not higher-dimensional numpy arrrays.

2019-01-06 23:13 UTC, dmlundeby commented on hyperspy/learn/mva.py
> -        if hasattr(self, 'output_dimension') and self.output_dimension \
Removed this check as it is included in the check [above](https://github.com/hyperspy/hyperspy/pull/2094/files#diff-cd68ac14189365f87b724293fa3c9f38R1285).

2019-01-10 16:20 UTC, francisco-dlp commented
The tests are failing due to #2120

2019-01-13 14:56 UTC, ericpre commented on hyperspy/learn/mva.py
> +            if isinstance(value, np.ndarray) and value.shape == ():
Ok, then would it be more specific (and clear) to use `value.ndim == 0`?

2019-01-13 17:06 UTC, dmlundeby commented on hyperspy/learn/mva.py
> +            if isinstance(value, np.ndarray) and value.shape == ():
Yes indeed. I've updated the branch now.

2019-01-14 18:23 UTC, ericpre approved these changes

2019-01-14 18:24 UTC, merged

2019-01-14 18:24 UTC, ericpre commented
Thanks!