Fix bug when adding multidimensional marker to signal with more than 2 navigation dimensions with different size
hyperspy/hyperspy pull request #2098
Opened 2018-11-20 16:19 UTC by magnunor

This pull request fixes a bug when adding multidimensional markers to a signal with 2+ navigation axes, where the axes does not have the same size. (https://github.com/hyperspy/hyperspy/issues/2080).

Essentially, either `BaseSignal.add_marker` has to be changed, or the internal mechanism in `MarkerBase` has to be changed: https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/drawing/marker.py#L166

I opted for changing `BaseSignal.add_marker`, since there is a smaller chance of breaking anything else...

### Changes

- `BaseSignal.add_marker`: marker navigation dimension will now have to be the inverse of the signal navigation dimension. So if the signal has nav dims (2, 3), the marker must be initialized with a list with shape (3, 2).
- Add unit test for checking this
- Add docstring to `BaseSignal.add_marker` for how to add markers to a signal like this

### Progress of the PR
- [x] Fix bug
- [x] Add docstring
- [x] Add tests
- [x] Ready for review

### Minimal example showing the bug

With the current RELEASE_next_patch, the marker will be added, however navigating to the right part of the navigation plot will give an `IndexError`.
```python
import numpy as np
import hyperspy.api as hs
s = hs.signals.Signal1D(np.arange(2*3*8).reshape(2, 3, 8))
marker_pos_list = np.array([[1, 2], [3, 4], [5, 6]])
marker0 = hs.markers.vertical_line(marker_pos_list, color='red')
s.add_marker(marker0, plot_signal=False, permanent=True)
s.plot()
s.axes_manager.indices = (2, 0)
```

Trying to "flip" the navigation dimensions to fix this, the marker raise a `ValueError` when using `s.add_marker`:

```python
import numpy as np
import hyperspy.api as hs
s = hs.signals.Signal1D(np.arange(2*3*8).reshape(2, 3, 8))
marker_pos_list = np.array([[1, 3, 5], [2, 4, 6]])
marker0 = hs.markers.vertical_line(marker_pos_list, color='red')
s.add_marker(marker0, plot_signal=False, permanent=True)
```

Using this pull request, the marker can be added, and plotted without giving the `IndexError`:
```python
import numpy as np
import hyperspy.api as hs
s = hs.signals.Signal1D(np.arange(2*3*8).reshape(2, 3, 8))
marker_pos_list = np.array([[1, 3, 5], [2, 4, 6]])
marker0 = hs.markers.vertical_line(marker_pos_list, color='red')
s.add_marker(marker0, plot_signal=False, permanent=True)
s.plot()
s.axes_manager.indices = (2, 0)
```

2018-11-21 13:40 UTC, magnunor commented
Might be of interest to `pyxem` (@dnjohnstone), if they use markers to show where peaks are located.

2018-12-14 22:14 UTC, ericpre requested changes
A couple of comments:
- the merge conflict need to be solved,
- the error message of your first example is now outdated and not correct anymore,
- it would have been nice to keep the consistency (same "shape" of the list) with the navigation shape,
- I find that the documentation is a bit confusing with respect of the shape of the marker list.

2018-12-14 22:14 UTC, ericpre commented on hyperspy/signal.py
> +        >>> s.plot(plot_markers=True) #doctest: +SKIP
when I run this example, the plot is displayed when the marker is added to the signal and there is no need to call `s.plot`. Is it expected? If so, the last line can be removed?

2018-12-14 22:14 UTC, ericpre commented on hyperspy/signal.py
> +        >>> marker = hs.markers.vertical_line([[1, 3, 5], [2, 4, 6]])
Maybe worth briefly explaining the "shape" of the list?

2018-12-14 22:14 UTC, ericpre commented on hyperspy/tests/drawing/test_plot_markers.py
> +    def test_add_marker_signal2d_navigation_dim(self):
Rename this test or the previous one: they both have the same name.

2019-05-20 19:03 UTC, magnunor commented
Merge conflict has been fixed, error message updated and docstring examples has been improved.

> it would have been nice to keep the consistency (same "shape" of the list) with the navigation shape,

Indeed, howeer that would require breaking the API. Which would land it in `RELEASE_next_major`, although this is a bug.

2019-05-21 09:44 UTC, francisco-dlp commented
LGTM, @ericpre ?

2019-05-21 10:21 UTC, magnunor commented
With regards to making the navigation shape and marker input shape the same, we could merge this pull request. Then have an additional pull request for `RELEASE_next_major`, which changes the internal behaviour.

2019-05-21 10:35 UTC, francisco-dlp commented
The thing is that HyperSpy uses internally C-order, just like numpy, so, I think that using C-order when passing arrays to HyperSpy objects is fine. A way to improve the interface of the markers would be to let them accept HyperSpy signals in addition to arrays. That would make it explicit that the dimensions are actually consistent with HyperSpy conventions.

2019-05-21 11:07 UTC, magnunor commented
> A way to improve the interface of the markers would be to let them accept HyperSpy signals in addition to arrays.

That is a pretty good idea! I'm slightly tempted to extend this pull request to handle signals as well, since it makes explaining the dimensions a lot easier. Maybe send it to `RELEASE_next_minor` instead.

2019-05-21 11:09 UTC, francisco-dlp commented
I think that this one is fine as it is, but we must wait to see if @ericpre agrees. The new feature should indeed go into a separate branch.

2019-05-21 11:55 UTC, ericpre approved these changes

2019-05-21 12:49 UTC, merged