Vacuum mask eels
hyperspy/hyperspy pull request #2183
Opened 2019-05-22 21:26 UTC by ericpre

Similarly to the way it can be currently done with `EDSSpectrum, this PR add a `vacuum_mask` method to the `EELSSpectrum` signal.

### Progress of the PR
- [x] Add `vacuum_mask` method to `EELSSpectrum`,
- [x] make the usage of mask more consistent across different method by accepting signal of bool or array of bool,
- [x] update docstring (if appropriate),
- [x] add tests,
- [x] ready for review.

### Minimal example of the bug fix or the new feature
```python
ll = hs.datasets.artificial_data.get_low_loss_eels_line_scan_signal()*100
ll.inav[:4] *= 0
ll.vacuum_mask().plot()
```

2019-07-25 14:00 UTC, dnjohnstone requested changes
Seems to work for me insofar as I understand it should from the tests provided.

It seems to me that for consistency there should be a super().decomposition() for EELSSpectrum in the same way that there is for EDSTEMSpectrum with a flag to use this method to determine a vacuum mask for decomposition as default.

Other than this, and minor typos - looks good to me

2019-07-25 14:00 UTC, dnjohnstone commented on hyperspy/_signals/eds_tem.py
> +        Return
Should probably be Returns rather than Return

2019-07-25 14:00 UTC, dnjohnstone commented on hyperspy/_signals/eels.py
> +            If true, applied a morphologic closing to the mask
If True, a morphological closing is applied to the mask.

2019-07-25 14:00 UTC, dnjohnstone commented on hyperspy/_signals/eels.py
> +            If true, applied a morphologic opening to the mask
If True, a morphologlical opening is applied to the mask.

2019-07-25 14:00 UTC, dnjohnstone commented on hyperspy/_signals/eels.py
> +        opnening: bool
Typo --> opening

2019-07-25 14:00 UTC, dnjohnstone commented on hyperspy/_signals/eels.py
> +            For a given pixel, mean value in the energy axis below which the
Perhaps "For a given navigation coordinate, the mean value in the energy axis..."

2019-07-25 14:00 UTC, dnjohnstone commented on hyperspy/_signals/eels.py
> +            Energy from which the intensity is averaged up to the end.
Minimum energy included in the calculation of the mean intensity.

2019-07-25 14:00 UTC, dnjohnstone commented on hyperspy/_signals/eels.py
> +            The mask of the region
fullstop at end.

2019-07-25 14:00 UTC, dnjohnstone commented on hyperspy/_signals/eels.py
> +    def richardson_lucy_deconvolution(self, psf, iterations=15,
Does this create a change in useage that needs documentation - or is it just a spurious kwarg that was actually not used properly in prior code?

2020-01-23 22:28 UTC, dnjohnstone commented
@ericpre can you deal with the very minor comments I had so that this can be merged?

2020-07-26 16:02 UTC, tjof2 reviewed
Aside from the comments from @dnjohnstone , there's a couple of merge conflicts.

2020-07-26 16:02 UTC, tjof2 commented on hyperspy/learn/mva.py
> +                navigation_mask = navigation_mask.data
This is probably a conflict with the recent decomposition overhaul

2020-09-08 10:38 UTC, tjof2 commented
Requires the merge conflicts to be resolved plus a few of the above comments

2020-09-11 09:58 UTC, tjof2 approved these changes

2020-09-11 09:59 UTC, tjof2 commented
Is that everything now @ericpre?

2020-09-11 10:15 UTC, ericpre commented
Yes, this is good now. Increasing coverage made me find a bug with the navigation mask of the `quantification` method!

2020-09-11 10:32 UTC, merged