Convert heaviside step function component to expression
hyperspy/hyperspy pull request #2262
Opened 2019-10-08 19:40 UTC by jlaehne

### Description of the change
Conversion of the heaviside step function component to an expression-based definition. As expression allows for only one `where`, this version follows the alternative definition without intermediate value at x=n. 

### Progress of the PR
- [X] Change implemented,
- [X] update docstring,
- [ ] add tests,
- [ ] ready for review.

### Minimal example of the bug fix or the new feature
```python
>>> import hyperspy.api as hs
>>> h1 = hs.model.components1D.HeavisideStep(A=3,n=2)
>>> x = np.arange(0,5,step=0.01)
>>> s = hs.signals.Signal1D(h1.function(x))
>>> s.axes_manager.signal_axes[0].axis = x
>>> s.plot()
>>> h1.print_current_values()
>>> # Your new feature...
```
Note that this example can be useful to update the user guide.

2019-10-08 19:44 UTC, jlaehne commented
As noted by @francisco-dlp in #2251, an alternative for the definition would be using numpy's `heaviside` function. However, this function does not allow a change of the zero point, so one would have to pamper with the x-axis to achieve a step at a different position than zero.

Note that `np.heaviside` does not necessarily include the intermediate value at the step:
`np.heaviside(np.arange(-1,1.5,0.5), 0.5)` versus `np.heaviside(np.arange(-1,1.2,0.2), 0.5)`.

2019-10-31 07:39 UTC, jlaehne commented
At the moment, the problem with `heaviside` defined as expression is that  `expression.py` cannot automatically calculate the gradient of the step function. Any ideas on that?

2020-01-23 22:13 UTC, dnjohnstone requested changes
Thanks @jlaehne 

The component written as an expression looks fine except for a minor docstring typo.

I suppose the documentation changes might be a conflict with something that's been merged since this PR was made, I reviewed them before thinking about that....

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/git.rst
> +on Github <https://github.com/hyperspy/hyperspy>`_.
You've used Github here at github elsewhere - it seems you were looking to standardise, so standardise.

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/git.rst
> +For developing the code the home of HyperSpy is on github and you'll see that
This is still odd wording... how about "The home of HyperSpy code development is on github..."

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/git.rst
> +Well GitHub is the public forum in which we manage and discuss development of
Why not just delete the "Well", and again with the different forms of GitHub capitalization.

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/git.rst
> +the code. More importantly, it enables every developer to utilise Git which is
I think this actually should be "use" and here you've used "Git" where elsewhere you've changed it to "git". There should also be a comma before a "which" here.

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/git.rst
> +You can learn all about Git `here <http://www.git-scm.com/about>`_!
Are you using Git or git?

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/git.rst
> +personal use.
Isn't this final sentence a bit repetitive?

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/index.rst
> -    git.rst
Why is that being removed?

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/intro.rst
> +works -- so read it well:
-- to - if you're doing that elsewhere

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/intro.rst
>  2. Got a problem? -- ask!
-- to -

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/intro.rst
> +3. Contribute—yes you can!
spaces around the -

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/intro.rst
> +guides or the website) is always in need of some care. Beside,
Just delete the "Beside(s),"

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/lazy_computations.rst
> +   does, but it's actually a new object -- might as well use ``da = da + 2``
-- to -

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/testing.rst
> +  parameters of the same function without having to write to much repetitive
this should be "too"

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/testing.rst
> +* It is good to check that the tests does not use too much of memory after
This is wrong and it was correct before. What a test does affects what the tests do.

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/testing.rst
> +  PR page. This service can help you to find how well your code is being tested
find --> determine

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/testing.rst
> +  to have a nicer look and feel of pytest in the console (encoding issue have
This was correct before.

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/testing.rst
> +tests. The references images are located in the folder defined by the argument
This is wrong and was correct before.

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/testing.rst
> +If you don't use the ``--mpl``, the code of the tests will be executed but the
I don't think you need the "the" but getting rid of the comma is good.

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/testing.rst
> +    1. Write the tests using appropriate decorator such as
This was correct before

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/testing.rst
> +    2. If you need to generate new reference image in the folder
If you're going to take the "a" away you need to make it "images"

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/testing.rst
> +When the plotting tests are failling, it is possible to download the figure
Should be "failing" here

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/testing.rst
> +variable and set accordingly the backend.
Should be "set the backend accordingly"

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/testing.rst
> +for easier viewing. I can be installed by conda:
"It" made more sense

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_docs.rst
> +Docstrings -- written at the start of a function and give essential information
-- to -

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_extensions.rst
> +Models can be provided by external packages too but don't need to
just delete the "too"

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_extensions.rst
> +At this point it is worth noting that HyperSpy's main strength is its amazing
Just delete the "At this point"

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_extensions.rst
> +matching project are essential for the sustainability of our software
I like the emphasis of "open" but not a big deal

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_extensions.rst
> +When and where create a new ``BaseSignal`` subclass
better with the "to"

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_extensions.rst
> +         D{Does an SignalxD for the required dimension exist in HyperSpy?}
should be "a"

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_extensions.rst
> +         H{Does an signal for that sort of data exists?}
should be "a"

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_extensions.rst
> +         D [label="Does an SignalxD for the required dimension exist in HyperSpy",shape="diamond"]
a

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_extensions.rst
> +         H [label="Does an signal for that sort of data exists?",shape="diamond"]
this was correct before

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_extensions.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
better with the "to"

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_extensions.rst
> +    packages developers to avoid ``signal_type`` clashes, typically by collaborating
this was correct before

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_extensions.rst
> +for your function you should consider creating your own.
ok to get rid of the comma but the word order was better before

2020-01-23 22:13 UTC, dnjohnstone commented on doc/dev_guide/writing_extensions.rst
> +      # toolkeys must start by the name of the packages that provides them.
this was better before.

2020-01-23 22:13 UTC, dnjohnstone commented on hyperspy/_components/heaviside.py
> +        Height parameter for x>n.
Should be >=n I think

2020-01-24 23:20 UTC, jlaehne commented on hyperspy/_components/heaviside.py
> +        Height parameter for x>n.
yep

2020-01-24 23:24 UTC, jlaehne commented
Thanks for the review @dnjohnstone and sorry for the confusion with the reverted changes in the documentation. My fault. It was basically reverting changes that have since been merged into RNM. I sorted that out now.

2020-02-06 18:32 UTC, dnjohnstone commented
Thanks @jlaehne - I think this PR is now fine. The failing test is, I think, unrelated so I would merge this.

2020-05-16 15:02 UTC, jlaehne commented
Test for the function was implemented, so not sure why Codecov fails?

2020-05-18 06:58 UTC, tjof2 commented
Codecov seems broken more generally

2020-06-29 11:32 UTC, tjof2 approved these changes

2020-06-30 07:16 UTC, merged