PEP8 style compliance
hyperspy/hyperspy pull request #2312
Opened 2020-01-25 05:00 UTC by dnjohnstone

The developer guide says that we follow PEP coding conventions: http://hyperspy.org/hyperspy-doc/current/dev_guide/coding_style.html

There are quite a few places where the code does not.

This PR introduces scripts "pepstrom.bat" and "pepstorm.sh" that iterate through the directory tree and use autopep8 to correct for easily made slips on these conventions. It also uses these scripts to tidy up the code.

To do:

- [ ] Introduce pepstorm scripts
- [ ] Make sure that they are iterating through correctly
- [ ] Update the developer guide to suggest people use the scripts prior to making any PR.

2020-01-27 16:33 UTC, tjof2 commented
I use [black](https://black.readthedocs.io/en/stable/index.html) which is typically a bit stricter than using autopep8, but for consistency (" vs ', line lengths, etc) is IMHO unrivalled. Perhaps that's a discussion for another day...

2020-01-27 16:48 UTC, dnjohnstone commented
I'd be up for switching to black - I like strict consistency for this kind of thing.

We could do it in this PR, would do the following:

- [ ] update the documentation to say we use the Black code style
- [ ] Run the code through black

@francisco-dlp @ericpre - opinions?

2020-01-27 17:20 UTC, ericpre requested changes
See comments on import.

2020-01-27 17:20 UTC, ericpre commented on hyperspy/api_nogui.py
> +from hyperspy import docstrings
Revert this changes: the logger needs to be imported and called before the rest.

2020-01-27 17:20 UTC, ericpre commented on hyperspy/samfire_utils/samfire_worker.py
>  matplotlib.rcParams['backend'] = 'Agg'
If the matplotlib backend is set before the import of hyperspy (and pyplot), I guess that there should be a reason. It not setting the matplotlib backend to `agg` should be removed.

2020-01-29 15:55 UTC, francisco-dlp commented
We've already passed the whole code through autopep8 once a while ago (just after the 1.0 release if I remember well). However, because not everybody uses ``autopep8`` and we don't check for compliance in the PRs, the situation today is not as good as it should be as this PR shows.

However, I think this is not the time to run the code through autopep8 again, because it makes merging the old PRs a nightmare. Since we are planning to merge as many PRs as possible before the split, I think that just before the split will be a good time to do this.

Once we go for it, I am also in favor of using black.

2020-01-29 16:51 UTC, ericpre commented
Black in combination with pre-commit would be good: https://black.readthedocs.io/en/stable/version_control_integration.html.

>However, I think this is not the time to run the code through autopep8 again, because it makes merging the old PRs a nightmare. Since we are planning to merge as many PRs as possible before the split, I think that just before the split will be a good time to do this.

I agree with postponing this for now to avoid creating additional merge conflicts.

2020-04-03 09:48 UTC, dnjohnstone commented
Given #2316 is now open and we will use black instead of autopep8 - I'm closing this.

2020-04-03 09:48 UTC, closed without merging