asymmetric lineshapes for eds and xrf fitting
hyperspy/hyperspy pull request #2326
Opened 2020-02-26 20:53 UTC by pquinn-dls

### Description of the change

In fitting XRF peaks an asymmetric peak is often needed to fit an elastic or compton peak.
I have implemented 
1) Doniach lineshape  - this is an asymmetric lineshape originally designed for XPS but
it fits tail like functions quite well
2) Split Voigt - this a voigt but a different sigma on the left and right of the centre

### Progress of the PR
- Doniach implemented as Expression,
- SplitVoigt implemented as Component
- docstrings with latex equations (if appropriate),
- tests implemented

- [ ] ready for review.

### Minimal example of the bug fix or the new feature
```python
>>> g1 = hs.components1D.Doniach(A=100.0,centre=0.0, sigma=1.0, alpha=0.1)
>>> g2 = hs.components1D.SplitVoigt(A=100.0,centre=0.0, sigma1=1.0,sigma2=2.0,fraction=0.1)

2020-02-27 10:04 UTC, pquinn-dls commented
Tests failing on CI due to tifffile... ?

2020-02-27 11:29 UTC, ericpre commented
> Tests failing on CI due to tifffile... ?

Yes, this is fixed in #2323.

xref #2269.

2020-02-27 12:05 UTC, pquinn-dls commented
@ericpre - sorry Eric it's not clear what I do next  - wait for the patch #2323 to merge  ?

2020-02-27 12:34 UTC, ericpre commented
For the moment, nothing to be done here with respect to the tiff tests. Once #2323 is merged, it may be worth merging the `RELEASE_next_minor` into this branch to get CI green.
In the meantime, this is less convenient than usual, because we need to check that only the tiff tests are failing, instead of relying on the CI tick boxes being green.

2020-04-03 16:28 UTC, francisco-dlp requested changes
Except for the Latex issues, this looks very good to me. I would only suggest adding the new components to the [list of components in the User Guide](https://hyperspy.org/hyperspy-doc/current/user_guide/model.html#creating-components-for-the-model).

2020-04-03 16:28 UTC, francisco-dlp commented on hyperspy/_components/doniach.py
> +        f(x)==\frac{cos[ \frac{{\pi\alpha}}{2}+
This equation doesn't compile properly using sphinx.

2020-04-03 16:28 UTC, francisco-dlp commented on hyperspy/_components/split_pvoigt.py
> +        pV(x,centre,\sigma) = (1 - \eta) G(x,centre,\sigma)
Same issue as with the other equation.

2020-04-05 11:20 UTC, francisco-dlp commented
@pquinn-dls, have you noticed https://github.com/pquinn-dls/hyperspy/pull/5?

2020-04-05 11:49 UTC, pquinn-dls commented
Sorry @francisco-dlp didn't see this and was working offline - I'll incorporate the changes, Thanks!

2020-04-05 14:15 UTC, merged