Fix "0" not being printed with print_current_values
hyperspy/hyperspy pull request #2331
Opened 2020-03-04 15:15 UTC by thomasaarholt

### Description of the change
When a value of a component's parameter is 0, it was not being printed by `m.print_current_values()`. Thanks to @erh3cq for bringing it to my attention.

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [ ] add tests,
- [ ] ready for review.

2020-03-18 12:06 UTC, thomasaarholt commented
Ready for review. The fix is very minor, but I've also added tests!

2020-04-02 09:05 UTC, tjof2 approved these changes

2020-04-03 15:46 UTC, francisco-dlp requested changes
LGTM except for some very minor style comments.

2020-04-03 15:46 UTC, francisco-dlp commented on hyperspy/misc/model_tools.py
> +    only_free : True or False, default False
``bool, default False``?

2020-04-03 15:46 UTC, francisco-dlp commented on hyperspy/misc/model_tools.py
> +    only_active : True or False, default False
as above

2020-04-03 15:46 UTC, francisco-dlp commented on hyperspy/misc/model_tools.py
> +    only_free : True or False, default False
as above

2020-04-03 15:46 UTC, francisco-dlp commented on hyperspy/misc/model_tools.py
> +    only_active : True or False, default False
as above

2020-04-03 15:46 UTC, francisco-dlp commented on hyperspy/misc/model_tools.py
> +                            for v in val]) + ")" if val != None else ""
stylistically ``is not None`` seems to be recommended over  ``!=None``

2020-04-03 15:46 UTC, francisco-dlp commented on hyperspy/tests/component/test_component_print_current.py
> +        self.component = self.model[1]
Where exactly are you testing for the bug fixed in this PR?

2020-07-01 21:54 UTC, ericpre commented
@thomasaarholt, this one should be quick to finish?

2020-07-10 13:34 UTC, thomasaarholt commented
Added @francisco-dlp's comments. Just waiting for tests to finish, should be good to go.

2020-07-10 13:42 UTC, thomasaarholt commented
On second look, I realised I hadn't added tests for the three helper functions I'd originally added.

2020-07-10 20:26 UTC, merged