Clarify documentation load functions
hyperspy/hyperspy pull request #2350
Opened 2020-04-03 17:55 UTC by ericpre

Recently, a few users have asked about the following error message (for example https://github.com/hyperspy/hyperspy-demos/issues/55#issuecomment-607525445):

```python
TypeError Traceback (most recent call last)
in
9 # <Signal2D, title: , dimensions: (|512, 512)>,
10 # <Signal2D, title: , dimensions: (|512, 512)>]
---> 11 s[0].plot()
```

### Progress of the PR
- [x] Clarify output of the load functions in its docstring and the user guide,
- [x] update docstring (if appropriate),
- [x] update user guide (if appropriate),
- [x] move the "interactive operations and ROI" section to its own page to give it more visibility,
- [x] fix a couple of warnings when building the documentation,
- [x] ready for review.

2020-04-03 20:17 UTC, dnjohnstone requested changes
Just some minor tweaks - then it's a please merge from me.

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/interactive_operations_ROIs.rst
> +The function :py:func:`~.interactive.interactive` ease the task of defining
--> simplifies the definition of....

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/interactive_operations_ROIs.rst
> +default it recomputes the operation when data or the axes of the original
By default the operation is recomputed when the data or...

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/interactive_operations_ROIs.rst
> +signal changes.
signal is changed.

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/interactive_operations_ROIs.rst
> +The interactive operations can be chained.
Interactive operations can be performed in a chain.

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/interactive_operations_ROIs.rst
> +***************************************************
Interactive and Region of Interest (ROI) Operations

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/interactive_operations_ROIs.rst
> +
ROIs can be defined to select part of any compatible signal and may be applied either to the navigation or to the signal axes.

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/interactive_operations_ROIs.rst
> +Once created, a ROI can be used to return a part of any compatible signal:
Once created, an ROI can be applied to the signal:

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/interactive_operations_ROIs.rst
> +The following examples shows how to interactively apply ROIs to an image. Note
The following example shows....

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/interactive_operations_ROIs.rst
> +By default output of the method is in degrees, though radians can be selected as follows:
The default output of the method...

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/interactive_operations_ROIs.rst
> +Conveniently, :meth:`~.roi.Line2DROI.angle` can be used to rotate image to align
can be used to rotate an image...

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/io.rst
> +If the loading was successful, the variable ``s`` contains a HyperSpy signal
If loading...

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/io.rst
> +If the loaded file contains some severals dataset, The ``load`` functions will
...contains several datasets, The load function will.....

2020-04-03 20:17 UTC, dnjohnstone commented on doc/user_guide/io.rst
> +    format that HyperSpy cannot read. Therefore, don't prune FEI EMD files in
....files if....

2020-04-03 20:17 UTC, dnjohnstone commented on hyperspy/io.py
> +    Depending ont the number of dataset in the file to load, this function will
...number of datasets to load in the file, this...

2020-05-16 22:34 UTC, jlaehne commented
LGTM

2020-05-17 07:43 UTC, francisco-dlp commented
LGTM too. Could you solve the conflicts?

2020-05-17 14:57 UTC, ericpre commented
Done.

2020-05-17 15:48 UTC, merged