Doc hyperspy main branches and rebase in the dev guide
hyperspy/hyperspy pull request #2565
Opened 2020-10-25 17:50 UTC by ericpre

Clarify the differences between the main branches in the hyperspy repository and explain how to rebase.

### Progress of the PR
- [x] update pull request template,
- [x] update dev guide,
- [x] ready for review.

2020-10-30 15:14 UTC, thomasaarholt requested changes
This is a nice addition! The links in the md file are outdated though.

2020-10-30 15:14 UTC, thomasaarholt commented on .github/PULL_REQUEST_TEMPLATE.md
> +* Base your pull request on the [correct branch](http://hyperspy.org/hyperspy-doc/current/dev_guide.html#semantic-versioning-and-hyperspy-main-branches).
These two links (lines 2 and 3) don't work. I realise that you create the "semantic.." heading in this PR, but the `dev_guide.html` file doesn't exist in the built docs.

2020-10-30 18:53 UTC, ericpre commented
Thanks for the review, the links are fixed.

2020-10-31 12:27 UTC, thomasaarholt approved these changes

2020-10-31 12:28 UTC, merged

2020-10-31 12:53 UTC, ericpre commented
Thanks @thomasaarholt!