Place qt navigator+signal plots side by side
hyperspy/hyperspy pull request #2584
Opened 2020-11-16 17:18 UTC by thomasaarholt

### Description of the change
I've offset the navigator and signal plots by half their widths left and right, so that they appear next to one another. The small annoyance of having to always drag the plots left and right has somewhat prevented me from embracing the qt backend, even though it is much, much faster than nbagg.

I'm a little unsure how this performs on other platforms - I can only test on windows. I've tried testing with the tk backend, but that seems to be acting strangely on my testing environment without the change this PR brings.

Finally, whether or not the plots appear in front of the notebook appears to be a bit ambiguous. When testing it, sometimes the plots start appearing behind the browser. A browser refresh oddly enough seems to fix this.

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [x] update docstring (if appropriate),
- [x] ready for review.

### Minimal example of the bug fix or the new feature
```python
# please try with different backends if you have them
%matplotlib qt
import hyperspy.api as hs
import numpy as np
s = hs.signals.Signal1D(np.random.random((10,10,10)))
s.plot()
```

2020-11-16 23:06 UTC, ericpre requested changes
This would be good indeed to improve the current situation!

> Finally, whether or not the plots appear in front of the notebook appears to be a bit ambiguous. When testing it, sometimes the plots start appearing behind the browser. A browser refresh oddly enough seems to fix this. If anyone knows why this happens, I'd appreciate it.

See https://github.com/matplotlib/matplotlib/issues/6378 but this may overwritten by the system (display server or window manager) setting.

2020-11-16 23:06 UTC, ericpre commented on hyperspy/drawing/mpl_he.py
> +    def arrange_windows(self):
This method should be private.

2020-11-16 23:06 UTC, ericpre commented on hyperspy/drawing/mpl_he.py
> +        self.arrange_windows()
This should be called only when there is a `navigator_plot` figure:
```suggestion
        if self.navigator_plot is not None:
            self.arrange_windows()
```

2020-11-16 23:06 UTC, ericpre commented on hyperspy/drawing/mpl_he.py
> +                    manager.window.setGeometry(left-width//2 ,top, width, height) # must take ints
Moving the window to `left-width//2` will not work when the window is already on the left hand side of the screen, which is the case my system (fedora) for the first figure... after this it goes to the right hand side of my current window...
It would be good to know what defined the initial position of the first window.

2020-11-18 17:01 UTC, thomasaarholt commented on hyperspy/drawing/mpl_he.py
> +                    manager.window.setGeometry(left-width//2 ,top, width, height) # must take ints
@ericpre what backend are you using? `plt.get_backend()`.

Also, what other backends do you think people actively use?

It looks like any code to set the positions will be all backend-specific.

2020-11-19 09:36 UTC, ericpre commented on hyperspy/drawing/mpl_he.py
> +                    manager.window.setGeometry(left-width//2 ,top, width, height) # must take ints
This is with the qt backend. I am not sure if other backend works with the traitsui widgets and the qt backend is most likely the one which works best, so I would worry too much about other backend for now.

2020-11-19 10:15 UTC, thomasaarholt commented on hyperspy/drawing/mpl_he.py
> +                    manager.window.setGeometry(left-width//2 ,top, width, height) # must take ints
I've realised I can use pillow to get the screen resolution. Not sure how it plays with multiple monitors. I'll have a play with placing the figures as a function of screen size and come up with a draft.

2020-11-19 10:23 UTC, ericpre commented on hyperspy/drawing/mpl_he.py
> +                    manager.window.setGeometry(left-width//2 ,top, width, height) # must take ints
Using pillow to do this as a workaround doesn't sound good. Maybe, a simple solution would be to set the left position to zero for the navigator and offset the signal plot with the width of the navigator?

2020-11-20 10:34 UTC, thomasaarholt commented
@ericpre can you try now? 
I agree that we don't want to use pillow - it seems to be only a dependency of the IO, and eventually (😄) that will be split off from the main hyperspy repo.

2020-11-23 18:05 UTC, ericpre commented
To play with this, we need to understand how it works and after reading more about it (https://doc.qt.io/qt-5/application-windows.html#window-geometry and https://www.riverbankcomputing.com/static/Docs/PyQt5/api/qtwidgets/qwidget.html), it doesn't give me confidence that it is clear what it is doing. By the way, the method used here to set the position of the window are qt specific.

2023-07-24 14:09 UTC, closed without merging