Lazy save improvement
hyperspy/hyperspy pull request #2797
Opened 2021-07-15 15:30 UTC by ericpre

### Progress of the PR
- [x] Add option to close file when saving lazy signal to hspy format,
- [x] add option not to write dataset, which can useful when saving large signal (hspy format only),
- [x] update docstring,
- [x] update user guide,
- [ ] add an changelog entry in the `upcoming_changes` folder (see [`upcoming_changes/README.rst`](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/upcoming_changes/README.rst)),
- [ ] Check formatting changelog entry in the `readthedocs` doc build of this PR (link in github checks)
- [x] add tests,
- [ ] ready for review.

### Minimal example of the bug fix or the new feature
```python
import hyperspy.api as hs
import numpy as np

s = hs.signals.Signal1D(np.arange(1000).reshape(10, 100))

fname = 'test.hspy'
s.save(fname, overwrite=True)

s2 = hs.load(fname, lazy=True, mode='a')
s2.axes_manager[-1].scale = 0.1
# write everything, except the dataset itself
s2.save(fname, overwrite=True, write_dataset=False)

s3 = hs.load(fname)
print(s3.axes_manager[-1].scale)
```

2021-10-04 08:36 UTC, jlaehne reviewed
some typos

2021-10-04 08:36 UTC, jlaehne commented on doc/user_guide/io.rst
> +  should not be close if the data need to be accessed lazily after saving.
closed

2021-10-04 08:36 UTC, jlaehne commented on hyperspy/io.py
> +        write. Useful to save attributes without having the write the whole
to write (not the write)

2021-10-04 08:36 UTC, jlaehne commented on hyperspy/io_plugins/hspy.py
> +        attributes without having the write the whole dataset. Default is True.
to write

2021-10-04 12:39 UTC, ericpre commented
I will come back to this after #2825 is merged.

2021-10-21 12:28 UTC, ericpre reviewed
The test suite is failing on python 3.6 and I think that it is not worth trying to get it to work because python 3.6 is not supported anymore and we should drop it in the next minor release.

2021-10-21 12:28 UTC, ericpre commented on hyperspy/io_plugins/_hierarchical.py
> -        if dset == data:
This is never used and it breaks with latest version of `h5py` (3.5).

2021-10-21 12:28 UTC, ericpre commented on hyperspy/io_plugins/zspy.py
> -    if ("write_to_storage" in kwds and kwds["write_to_storage"]) or isinstance(filename, MutableMapping):
This was actually not working as expected when opening a file which has been saved with a store different than the `NestedDirectoryStore` or `DirectoryStore`, because `zarr` is initialising the correct store based on the extension (https://github.com/zarr-developers/zarr-python/blob/523dbb85cbad5a5fa3b74a2ec81ec7ec63123b64/zarr/creation.py#L160-L178). For this reason, I remove it here.

2021-10-21 12:28 UTC, ericpre commented on hyperspy/io_plugins/zspy.py
> -            path = group._store.dir_path() + "/" + dset.path
Using `zarr` group private attribute is asking for trouble!
@CSSFrancis, in #2825, you mentioned that this was necessary in some cases? I have extended the test coverage and this seems to be working fine and I think that this use of the API is supported, so if this doesn't work, it could be a bug somewhere else.
Can you please check?

2021-10-21 12:37 UTC, ericpre commented
@CSSFrancis, would you like to review this PR? Thanks!

2021-10-21 13:15 UTC, CSSFrancis commented on hyperspy/io_plugins/_hierarchical.py
> -        if dset == data:
That is good to know.  I figured that was left over from previous version but it wasn't tested so I didn't know if there was a case where it was important.

2021-10-21 13:29 UTC, CSSFrancis commented
> @CSSFrancis, would you like to review this PR? Thanks!

Yea let me see if I can get to this today or tomorrow

2021-10-21 14:13 UTC, CSSFrancis commented on hyperspy/io_plugins/zspy.py
> +            da.store(data, dset)
```suggestion
            da.store(data, dset, lock=False)
```

2021-10-21 14:41 UTC, CSSFrancis requested changes
@ericpre Looks like this cleans up a lot of the little things that I wasn't terribly confident about and reduces the code complexity a fair bit! Thanks for doing this. 

One note (as I said above) is that the `store` function doesn't play well with dask.distrubted unless lock=False.  It might be worth adding in some tests for compatibility there if the goal is to fully integrate with dask, but I am not sure how easy deploying something like that on a testing environment is. 

I assume that replacing `create_group` with `require_group` is preferable because if won't throw an error if the group already exists?

Other than that, one of the tests which tested passing a Mutable Mapping object as the file name was deleted and should be covered.

2021-10-21 14:41 UTC, CSSFrancis commented on hyperspy/io_plugins/zspy.py
> -            path = group._store.dir_path() + "/" + dset.path
So the issue arises when using a dask.distributed scheduler. The solution is to set lock = False.  I didn't realize this when I originally wrote the code.  It might be worth writing tests in the future to test dask.distrubted compatibility if we are planning to fully support it (Which I would recommend)

2021-10-21 14:41 UTC, CSSFrancis commented on hyperspy/io_plugins/zspy.py
> -            path = group._store.dir_path() + "/" + dset.path
It seems like the pickling is intending to be thread safe so it throws an error if lock is set to True

2021-10-21 14:41 UTC, CSSFrancis commented on hyperspy/io_plugins/zspy.py
> -    if ("write_to_storage" in kwds and kwds["write_to_storage"]) or isinstance(filename, MutableMapping):
Ahh, very true.  Removing the write to storage argument should be fine.

2021-10-21 14:41 UTC, CSSFrancis commented on hyperspy/tests/io/test_zspy.py
> -
This should not be deleted I think.  You can remove the `write_to_storage=True` but this test shows if passing a MutableMapping object works for saving the data.

2021-10-21 18:11 UTC, ericpre commented
Thanks for the review!

> One note (as I said above) is that the store function doesn't play well with dask.distrubted unless lock=False. It might be worth adding in some tests for compatibility there if the goal is to fully integrate with dask, but I am not sure how easy deploying something like that on a testing environment is.

Yes, this is what dask is doing too: https://github.com/dask/dask/blob/62f96e7edb27cb94eca49d5ac2f5639fb8cca44a/dask/array/core.py#L3388

> I assume that replacing create_group with require_group is preferable because if won't throw an error if the group already exists?

Yes, this is correct, same for `h5py` and [`zarr`](https://zarr.readthedocs.io/en/stable/api/hierarchy.html?highlight=require_group#zarr.hierarchy.Group.require_group).

> Other than that, one of the tests which tested passing a Mutable Mapping object as the file name was deleted and should be covered.

As mentioned in https://github.com/hyperspy/hyperspy/pull/2797#discussion_r733619173, this was not working correctly, but I had a look at it again, one way to get it to work is to pass store of the same in the `load` function.

It should be all good now!

2021-10-21 18:41 UTC, ericpre commented on hyperspy/io_plugins/zspy.py
> -            path = group._store.dir_path() + "/" + dset.path
> So the issue arises when using a dask.distributed scheduler. The solution is to set lock = False. I didn't realize this when I originally wrote the code. It might be worth writing tests in the future to test dask.distrubted compatibility if we are planning to fully support it (Which I would recommend)

Yes, it would be good to have some tests using `dask.distributed.Client`. I don't know how well it will play in CI and I had a quick look at how dask are testing it, and I didn't understood straightaway, so I would leave it for another PR! :)

2021-10-22 11:25 UTC, ericpre commented on hyperspy/io_plugins/hspy.py
> +overwrite_dataset = HyperspyWriter.overwrite_dataset
`overwrite_dataset` is actually part of the public API, so I put back here... it was breaking kikuchipy, as pointed out by https://github.com/hyperspy/hyperspy/runs/3973795422?check_suite_focus=true!

2021-10-22 11:29 UTC, ericpre commented
Running the integration test suite show that it was breaking the public API... see https://github.com/hyperspy/hyperspy/pull/2797#discussion_r734456427. This is fixed in caf6a01.

@CSSFrancis, does it look good to you?

2021-10-25 13:45 UTC, CSSFrancis commented
> @CSSFrancis, does it look good to you?

Yea with the changes it looks good! Thanks for cleaning this stuff up.

2021-10-26 12:27 UTC, hakonanes commented on hyperspy/io_plugins/hspy.py
> +overwrite_dataset = HyperspyWriter.overwrite_dataset
Very good catch, thanks a lot.

2021-10-27 14:28 UTC, ericpre commented
@jlaehne, do you want to do another review of this PR?

2021-10-27 21:32 UTC, jlaehne commented on hyperspy/io.py
> +        Only for hspy files. Define the chunking used for saving the dataset.
In the user guide it says these extra arguments are only relevant for `zarr` format, here it says they are only relevant for `hspy` format. Also some details in the description differ between here and io.rst.

2021-10-27 21:56 UTC, jlaehne commented
> @jlaehne, do you want to do another review of this PR?

I sent a PR correcting some typos. There are still some codecov warnings (mostly about untested exceptions). Otherwise nothing that caught my eye.

2021-10-27 22:10 UTC, jlaehne commented on hyperspy/io_plugins/_hierarchical.py
> +        the shape of the dataset to be sored / chunked
sorted or stored ?

2021-10-29 13:23 UTC, ericpre commented on hyperspy/io.py
> +        Only for hspy files. Define the chunking used for saving the dataset.
Yes, this docstring is for `save`, not `load`! :facepalm:

2021-10-29 13:25 UTC, ericpre commented
Thanks @jlaehne, I increased the coverage and fixed the docstring.

2021-10-29 16:10 UTC, magnunor reviewed
I tested this on my own computer, and I'm getting an error:

```python
import dask.array as da
import hyperspy.api as hs

s = hs.signals.Signal1D(da.random.random((10, 20, 50))).as_lazy()
s.save("test_dataset.hspy")
```
Giving the error:
```python
hyperspy/io_plugins/_hierarchical.py in overwrite_dataset(cls, group, data, key, signal_axes, chunks, **kwds)
    574                     # we delete the old one and create new in the next loop run
    575                     del group[key]
--> 576         if dset == data:
    577             # just a reference to already created thing
    578             pass

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I do have a bit of a strange mix of package versions, so it could be caused by that.

2021-10-29 16:10 UTC, magnunor commented on doc/user_guide/io.rst
> +- ``chunks``: tuple of interger or None. Define the chunking used for saving
Typo: should be integer

2021-10-29 16:10 UTC, magnunor commented on hyperspy/io_plugins/_hierarchical.py
> +    signal_axes: {None, iterable of ints}
signal_axes : {None, iterable of ints}

2021-10-29 16:10 UTC, magnunor commented on hyperspy/io_plugins/_hierarchical.py
> +    target_size: int
target_size : int

2021-10-29 16:10 UTC, magnunor commented on hyperspy/io_plugins/_hierarchical.py
> +    An object used to simplify and orgainize the process for writing a
```suggestion
    An object used to simplify and organize the process for writing a
```

2021-10-29 16:10 UTC, magnunor commented on hyperspy/io_plugins/_hierarchical.py
> +    Hierachical signal, such as hspy/zspy format.
```suggestion
    Hierarchical signal, such as hspy/zspy format.
```

2021-10-29 16:10 UTC, magnunor commented on doc/user_guide/io.rst
> +  a compresssor can be passed to the save function to compress the data efficiently. The default
```suggestion
  a compressor can be passed to the save function to compress the data efficiently. The default
```

2021-10-29 16:26 UTC, ericpre commented
> I tested this on my own computer, and I'm getting an error:
> 
> ```python
> import dask.array as da
> import hyperspy.api as hs
> 
> s = hs.signals.Signal1D(da.random.random((10, 20, 50))).as_lazy()
> s.save("test_dataset.hspy")
> ```
> 
> Giving the error:
> 
> ```python
> hyperspy/io_plugins/_hierarchical.py in overwrite_dataset(cls, group, data, key, signal_axes, chunks, **kwds)
>     574                     # we delete the old one and create new in the next loop run
>     575                     del group[key]
> --> 576         if dset == data:
>     577             # just a reference to already created thing
>     578             pass
> 
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> ```
> 
> I do have a bit of a strange mix of package versions, so it could be caused by that.

Thanks @magnunor! It seems that you are on a wrong branch, the code at line 576 is different in this branch:
https://github.com/ericpre/hyperspy/blob/9c5bf6fa1550867eee8a586ad4a8d163d38f4f2a/hyperspy/io_plugins/_hierarchical.py#L576

2021-10-29 16:48 UTC, magnunor commented
> It seems that you are on a wrong branch, the code at line 576 is different in this branch:

Indeed! Seems like `git` had changed how it handled pulling branches from a remote, so this,

```
git checkout -b ericpre-lazy_save_improvement RELEASE_next_minor
git pull https://github.com/ericpre/hyperspy.git lazy_save_improvement
```
failed.

2021-10-29 18:35 UTC, magnunor reviewed
I got the previous issue sorted out, and tested the functionality a little bit. Some observations:

- `write_dataset=False` for updating both `hspy` and `zspy` files works fine, for both `axes_manager` and `metadata`
- `zspy` does not require loading the data with any specific `mode`. As opposed to `hspy`, which requires `mode="a"`
- The filename can be dropped when doing `s.save(overwrite=True, write_dataset=False)`
- Loading via `zspy` is much faster, both using `DirectoryStore` and `LMDBStore`. For a 512 x 512 x 256 x 256 dataset, with uint16, it took about 20 seconds. The same dataset took about 100 seconds with `hspy`

This is probably unrelated, but doing:

```python
s = hs.load("test_data.hspy", lazy=True)
s.compute()
```
used two times as much memory (64 GB), as opposed to `s = hs.load("test_data.hspy", lazy=False)`, which used 32 GB.

This is using the most recent version of `dask`, `2021.10.0`

2021-10-29 18:35 UTC, magnunor commented on hyperspy/io_plugins/_hierarchical.py
> +        Initalizes a general reader for hierarchical signals.
```suggestion
        Initializes a general reader for hierarchical signals.
```

2021-10-29 18:35 UTC, magnunor commented on hyperspy/io_plugins/hspy.py
> +    An object used to simplify and orgainize the process for
```suggestion
    An object used to simplify and organize the process for
```

2021-10-29 18:35 UTC, magnunor commented on doc/user_guide/io.rst
> +        Compression can significantly increase the saving speed. If file size is not
Is this sentence correct? Or at least ambiguous?

I'm guessing it should say that using compression can cause file saving and loading to be much slower.

2021-10-29 18:44 UTC, ericpre commented on doc/user_guide/io.rst
> +        Compression can significantly increase the saving speed. If file size is not
Yes, this is correct in many cases when the IO time is balanced against with the CPU time - most of the time, CPU are fast enough and compressor are efficient enough.

2021-10-29 18:53 UTC, ericpre commented
> This is probably unrelated, but doing:
> 
> ```python
> s = hs.load("test_data.hspy", lazy=True)
> s.compute()
> ```
> 
> used two times as much memory (64 GB), as opposed to `s = hs.load("test_data.hspy", lazy=False)`, which used 32 GB.
> 
> This is using the most recent version of `dask`, `2021.10.0`

Yes, this is not related to this PR - at least I don't see how it can be and I would expect that the same happen with other branches. Do you observe the same memory usage with `zspy`?

2021-10-30 11:46 UTC, ericpre commented
Thanks @CSSFrancis, @jlaehne and @magnunor for the reviews, I will merge this PR to be able to rebase https://github.com/hyperspy/hyperspy/pull/2839 and fix CI, so that it is easier to work on #2842 and co.

2021-10-30 11:47 UTC, merged

2021-10-31 07:33 UTC, magnunor commented
> Yes, this is not related to this PR - at least I don't see how it can be and I would expect that the same happen with other branches. Do you observe the same memory usage with zspy?

Yes, this was also with `zspy`.