Impulse io
hyperspy/hyperspy pull request #2828
Opened 2021-09-27 13:46 UTC by DENSmerijn

### Description of the change
- Added Impulse csv file reader
- Added Impulse reader test script and data
- Updated documentation
- Modified other csv file reader (PC) to include the 'protochips' file extension (required to specify which csv reader is used)

### Progress of the PR
- [ ] Change implemented (can be split into several points),
- [ ] update docstring (if appropriate),
- [ ] update user guide (if appropriate),
- [ ] add an changelog entry in the `upcoming_changes` folder (see [`upcoming_changes/README.rst`](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/upcoming_changes/README.rst)),
- [ ] Check formatting changelog entry in the `readthedocs` doc build of this PR (link in github checks)
- [ ] add tests,
- [ ] ready for review.

### Minimal example of the bug fix or the new feature
```python
import hyperspy.api as hs
hs.load('ImpulseLogfile.csv', reader='impulse')
```

2021-10-04 22:14 UTC, ericpre requested changes
This looks good, it needs minor improvement. I added comments/suggestions and push a [pull request](https://github.com/DENSsolutions/hyperspy/pull/1) to this branch.

It will need a changelog entry too.

2021-10-04 22:14 UTC, ericpre commented on doc/user_guide/io.rst
>  ---------------
Sphinx will raise warning about the title underline being too short.

2021-10-04 22:14 UTC, ericpre commented on doc/user_guide/io.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Same as above: the title underline needs to match the length of the title.

2021-10-04 22:14 UTC, ericpre commented on hyperspy/io_plugins/impulse.py
> +            if quantity_split[-1][0] == "(" and quantity_split[-1][-1] == ")":
This two `if` statement could be merged.

2021-10-04 22:14 UTC, ericpre commented on hyperspy/io_plugins/impulse.py
> +            return False
```suggestion
        return "TimeStamp" in self.column_names and len(self.column_names) >= 3
```

Since this is short is used only once, I would put it directly where it is used: avoiding redirection is usually more readible.

2021-10-04 22:14 UTC, ericpre commented on hyperspy/io_plugins/impulse.py
> +        for i, name, name_dtype in zip(range(len(names)), self.column_names, names):
```suggestion
        for i, (name, name_dtype) in enumerate(zip(self.column_names, names)):
```

2021-10-04 22:14 UTC, ericpre commented on hyperspy/io_plugins/impulse.py
> +                    )
This is not used.

2021-10-04 22:14 UTC, ericpre commented on hyperspy/io_plugins/impulse.py
> +        return {"value": self.time_axis, "units": self.time_units}
This is not used, better not to keep it.

2021-10-04 22:14 UTC, ericpre commented on hyperspy/io_plugins/impulse.py
> +class impulseCSV:
Python class name follows CapWords convention.
```suggestion
class ImpulseCSV:
```

2021-10-04 22:14 UTC, ericpre commented on hyperspy/io_plugins/impulse.py
> +        except BaseException:
I am not convinced, that it is necessary to catch the exception here, because at this point, we already checked that it is supposedly a valid impulse file. One major drawback of catching the error is that it is more inconvenient to find where the error come from because the information about the original error is lost: this can be particular inconvenient when trying to help an user.

2021-10-04 22:14 UTC, ericpre commented on hyperspy/io_plugins/impulse.py
> +                return quantity_split[-1]
Is it expected that this is not covered by the tests?

2021-10-04 22:14 UTC, ericpre commented on hyperspy/io_plugins/impulse.py
> +                "quantity": self._parse_quantity_units(quantity),
Usually, when a metadata is not know, we don't populate it.

2021-10-04 22:14 UTC, ericpre commented on hyperspy/io_plugins/impulse.py
> +            return "NA"
`'NA'` can be ambiguous: better to return an empty string, or not to populate the metadata.

2021-10-04 22:14 UTC, ericpre commented on hyperspy/io_plugins/impulse.py
> +                raise IOError(no_metadata_file_error)
Even if there is no metadata file or it is corrupted, it would still be useful to be able to open the file? Maybe simply add a warning?

2021-10-04 22:14 UTC, ericpre commented on hyperspy/io_plugins/impulse.py
> +        self.time_units = "Seconds"
Since `_get_metadata_time_axis` is not used, this should be removed too.

2021-10-07 13:45 UTC, DENSmerijn commented
Hi ericpre, 

Thanks for reviewing the code, I believe all your suggested improvements were implemented now.

~ Merijn

2021-10-07 16:00 UTC, ericpre approved these changes
Yes, all good, thanks!

2021-10-07 19:04 UTC, merged