Fix bug with plot close/open cycle and permanent markers
hyperspy/hyperspy pull request #3234
Opened 2023-09-26 17:56 UTC by ericpre

First follow up of #3148 - hopefully, there will *not* be many! 😅

2023-10-05 21:30 UTC, CSSFrancis requested changes
The reversing needs to happen in order to account for the reverse ordering with respect to array/plotting. 

At the very least we should maybe make this addition to the `test_find_peaks` function.


```python 
    def test_find_peaks(self):
        from skimage.draw import disk
        from skimage.morphology import disk as disk2
        rr, cc = disk(
            center=(10, 8),
            radius=4,
        )
        img = np.zeros((2,2, 20, 20))
        img[:,:, rr, cc] = 1
        img[1,0] = 0
        s = Signal2D(img)
        s.axes_manager.signal_axes[0].scale = 1.5
        s.axes_manager.signal_axes[1].scale = 2
        s.axes_manager.signal_axes[0].offset = -1
        s.axes_manager.signal_axes[1].offset = -1
        pks = s.find_peaks(
            interactive=False,
            method="template_matching",
            template=disk2(4),
        )
        col = Points.from_signal(
            pks, sizes=(10,), signal_axes=s.axes_manager.signal_axes
        )
        s.add_marker(col)
        np.testing.assert_array_equal(col.get_current_kwargs()["offsets"], [[11, 19]])
        a = s.axes_manager.indices = (0,1) 
        np.testing.assert_array_equal(col.get_current_kwargs()["offsets"], [[np.nan, np.nan]])
```

2023-10-05 21:30 UTC, CSSFrancis commented on hyperspy/drawing/markers.py
> -            indices = self._axes_manager.indices[::-1]
This is currently causing the `from_signal` method to silently fail.  You need to reverse the indexes to follow the array--> plotting specification.

2023-10-06 13:12 UTC, ericpre commented
Thank you @CSSFrancis, the example that you gave here illustrate clearly the issue! I used an another approach: transpose the data array (only when ragged, because static marker don't have navigation dimension). I added tests to check the navigation shape for all relevant.

2023-10-06 13:15 UTC, CSSFrancis commented
@ericpre ahh perfect!  I was apparently only thinking about the ragged case when I wrote that 😅 The added test is great!

This looks good as long as the CI passes.

2023-10-06 13:16 UTC, CSSFrancis approved these changes

2023-10-09 15:52 UTC, merged